apiVersion: v1
data:
  conf.py: |
    # DeploymentResources that will be used during check
    from updater.resources import DeploymentResource

    DEPLOYMENTS = [
        DeploymentResource(organization="vladmalynych",
                           repository="image-updater-test",
                           tag_regex="^v([0-9]+)$",
                           deploy_name="image-updater-test",
                           namespace="default"),
    ]
kind: ConfigMap
metadata:
  name: k8s-image-updater-cm
